version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # Our config overwrites the config in the container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # This is the log folder
      - ./nginx/logs:/var/log/nginx/
      # This is the cache folder
      - ./nginx/cache/:/data/nginx/cache
    networks:
      - OurDockerNetwork

networks:
  OurDockerNetwork:
    external: true
